# Generated by Django 4.2.28 on 2026-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_status_room_image_room_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='A cozy room perfect for your stay.'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('pending', 'Pending'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('deluxe_suite', 'Deluxe Suite'), ('executive_suite', 'Executive Suite'), ('presidential_suite', 'Presidential Suite')], default='deluxe_suite', max_length=50),
        ),
    ]
