# Generated by Django 6.0.1 on 2026-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='nights',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
