# Generated by Django 6.0.1 on 2026-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_booking_status_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nights',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
